// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lymcpretqgxfubagjcfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5bWNwcmV0cWd4ZnViYWdqY2ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDIwMDEsImV4cCI6MjA1ODQ3ODAwMX0.xdbUqyRPssJVp6ibNLHPc-bKk44wT1x8rE2uuzVxmGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);